### ISSUE TITLE
SEON SDK getting stuck on `getFingerprintBase64()` because `SeonCallback` is not returning on version 6.3.0+

### ISSUE THREAD

**Issue by jnelsonBranch** [seontechnologies/seon-android-sdk-public#36]
When trying to upgrade the SDK version for our Android app recently, we noticed an issue with the SDK getting stuck on `getFingerprintBase64()` because the `SeonCallback` is not returning anything. We were trying to upgrade our SDK version to 6.4.0 (and also tried upgrading to 6.3.0) by following the Installation guide in the README.  This required us to exclude the `org.bouncycastle` files to prevent the duplicate class errors just like you guys called out. After getting the app to run with the upgraded SDK, we noticed infinite loaders caused by the SEON SDK getting stuck trying to retrieve the device fingerprint. Any help trying to get this resolved would be greatly appreciated. 

Note: Our Android app in production is currently using SEON SDK version 6.2.0 without issues.

**Comment by robertorsulics-seon** [comment]
Hi @jnelsonBranch ! Thanks for reporting this issue we're going to look into this. First off we would like to ask for some details, can you please help us by providing us what type and version of bouncycastle your app integrates? The other dependencies would be help as well if you're able to disclose them. Also an integration snippet would be great so we can start to reproduce your environment as closely as possible.

**Comment by jnelsonBranch** [comment]
Hi @robertorsulics-seon, it looks like we are integrating `bcprov-jdk15to18-1.69` based on this error message we get when we don't exclude it:
```
Caused by: java.lang.RuntimeException: Duplicate class org.bouncycastle.LICENSE found in modules bcprov-jdk14-1.77.jar -> bcprov-jdk14-1.77 (org.bouncycastle:bcprov-jdk14:1.77) and bcprov-jdk15to18-1.69.jar -> bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
```
After looking at our dependency tree, it looks like `bcprov-jdk15to18-1.69` is being brought in by this other dependency: `com.plaid.link:sdk-core:4.4.0`

```
|    |    +--- com.plaid.link:sdk-core:4.4.0
...
|    |    |    +--- org.bouncycastle:bcpkix-jdk15to18:1.69
|    |    |    |    +--- org.bouncycastle:bcprov-jdk15to18:1.69
|    |    |    |    \--- org.bouncycastle:bcutil-jdk15to18:1.69
|    |    |    |         \--- org.bouncycastle:bcprov-jdk15to18:1.69

```

For your information, we're also using version catalogs and updated `.kts` gradle build files. Here's a snippet showing you how we are implementing the SDK for this particular module (we are using multi module app architecture).
```
dependencies {
    implementation(libs.seon) {
        exclude(group = "org.bouncycastle", module = "bcprov-jdk14")
        isTransitive = true
    }
}
```

Let me know if you need any more information from me!

**Comment by robertorsulics-seon** [comment]
Hey @jnelsonBranch ! Thanks for the extra info, we could pinpoint the issue. 

The Plaid SDK you guys are using [links a 3 year old version](https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk15to18/1.69) of the bouncy castle dependency and our internals have used a method which doesn't exist in versions before 1.70. 

We have released a fix for this with `6.4.1` by shadowing our dependency of bouncy castle to avoid future conflicts and issues with the fingerprint function when there's another bouncy castle dependency present either directly or transitively.

We would really appreciate if you could still confirm that `6.4.1` has fixed the issue for you.

**Comment by jnelsonBranch** [comment]
Hey @robertorsulics-seon, that seemed to do the trick! Not seeing the any issues after upgrading to `6.4.1` 🎉 . Thank you for all your help getting this resolved!

**Comment by robertorsulics-seon** [comment]
Great to hear! Thanks for raising the issue !
